name: Run Tests

on: [ push ]

env:
  IMAGE_NAME: tdmproject/tdm-ingestion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nose kafka-python==1.4.7
          pip install -e .[confluent]
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      -
        name: Run unit tests
        run: nosetests tests/unit/ --with-coverage --cover-package tdm_ingestion
      -
        name: Build Docker Image for Tests
        run: docker build -f Dockerfile -t ${IMAGE_NAME} .
      -
        name: Run Integration Tests
        run: make tests_no_image
      -
        name: Set up Docker Buildx
        if: ${{ github.ref == 'refs/heads/master' && github.repository == 'tdm-project/tdm-ingestion' }}
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/master' && github.repository == 'tdm-project/tdm-ingestion' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      -
        name: Build and push
        if: ${{ github.ref == 'refs/heads/master' && github.repository == 'tdm-project/tdm-ingestion' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tdmproject/tdm-ingestion:latest,tdmproject/tdm-ingestion:1.0.12
      -
        name: Image digest
        if: ${{ github.ref == 'refs/heads/master' && github.repository == 'tdm-project/tdm-ingestion' }}
        run: echo ${{ steps.docker_build.outputs.digest }}
