name: Python Unit Testing

on: [ push ] 

env:
  IMAGE_NAME: tdmproject/tdm-ingestion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nose kafka-python==1.4.7
        pip install -e .[confluent]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run unit tests
      run: |
        nosetests tests/unit/ --with-coverage --cover-package tdm_ingestion
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile
    - name: Run Integration Tests
      run: |
        make tests_no_image
